# -*- coding: utf-8 -*-
"""downloadSongsYoutube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lzdCiKqaXg-1WQDlkA-iivxE-9jBIWCg
"""

#Install requirements
pip install youtube-dl

from __future__ import unicode_literals
import youtube_dl
import os
from google.colab import files


def download_song(song_url, song_index):
    """
    Download a song using youtube url and song title
    """
    #Get title
    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [
            {'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3',
             'preferredquality': '192',
             },
            {'key': 'FFmpegMetadata'},
        ],
    }

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        info_dict = ydl.extract_info(song_url, download=False)
        video_title = info_dict.get('title', None)

    #Set song title
    outtmpl = song_index + "_" + video_title + '.%(ext)s'

    #Set options
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': outtmpl,
        'postprocessors': [
            {'key': 'FFmpegExtractAudio','preferredcodec': 'mp3',
             'preferredquality': '192',
            },
            {'key': 'FFmpegMetadata'},
        ],
    }

    #Download youtube song from url
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        info_dict = ydl.extract_info(song_url, download=True)

    #Locally download the song
    files.download(song_index + "_" + video_title + ".mp3")



linksVideoToDownload = ['https://www.youtube.com/...',
                        'https://www.youtube.com/...',
                        


                       ]


for k, link in enumerate(linksVideoToDownload):
    download_song(link, str(k+1))